[cdn]
    build_command = "yarn run build"
    build_output = "dist"

[matchmaker]
	max_players = 128
	tier = "basic-1d8"
	idle_lobbies = { min = 0, max = 0 }

[matchmaker.regions]
	lnd-atl = {}
	lnd-fra = {}

[matchmaker.game_modes]
    [matchmaker.game_modes.default]

    [matchmaker.game_modes.custom]
        idle_lobbies = { min = 0, max = 0 }

        [matchmaker.game_modes.custom.actions]
            create = { enabled = true }

[matchmaker.docker]
	dockerfile = "Dockerfile"
	
	[matchmaker.docker.ports]
		default = { port = 8080, protocol = "https" }

[kv]
